/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.ClientController;
import domain.Cena;
import domain.JedinicaMere;
import domain.Pice;
import domain.VrstaPica;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import models.TableModelCena;

/**
 *
 * @author 38169
 */
public class IzmeniPiceForm extends javax.swing.JDialog {

    Pice pice;
    Cena cenaIzmena;
    boolean cuvanje = true;

    public void setPice(Pice pice) {
        this.pice = pice;
    }

    /**
     * Creates new form IzmeniPiceForm
     */
    public IzmeniPiceForm(java.awt.Frame parent, boolean modal, Pice pice) {
        super(parent, modal);
        initComponents();
        setTitle("Forma izmeni pice");
        setLocationRelativeTo(null);
        this.pice = pice;
        prepareData();
        TableModelCena tmc = new TableModelCena(pice);
        Thread t = new Thread(tmc);
        t.start();
        tblCena.setModel(tmc);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTrenutnaCena = new javax.swing.JFormattedTextField();
        txtDatumDo = new javax.swing.JFormattedTextField();
        cmbJM = new javax.swing.JComboBox();
        btnIzmeniPice = new javax.swing.JButton();
        cmbVrstaPica = new javax.swing.JComboBox();
        btnSacuvajCenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCena = new javax.swing.JTable();
        btnIzmeniCenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnObrisiCenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIznosCene = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNazivPica = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtKolicina = new javax.swing.JFormattedTextField();
        txtIDatumOd = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtTrenutnaCena.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        txtDatumDo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy."))));

        btnIzmeniPice.setText(" Izmeni pice");
        btnIzmeniPice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPiceActionPerformed(evt);
            }
        });

        btnSacuvajCenu.setText("Sacuvaj cenu");
        btnSacuvajCenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajCenuActionPerformed(evt);
            }
        });

        tblCena.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCena);

        btnIzmeniCenu.setText("Izmeni cenu");
        btnIzmeniCenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniCenuActionPerformed(evt);
            }
        });

        jLabel1.setText("Naziv pica:");

        btnObrisiCenu.setText("Obrisi cenu");
        btnObrisiCenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiCenuActionPerformed(evt);
            }
        });

        jLabel2.setText("Kolicina na stanju:");

        jLabel6.setText("Lista cena:");

        jLabel3.setText("Jedinica mere:");

        jLabel7.setText("Iznos:");

        jLabel4.setText("Vrsta pica:");

        txtIznosCene.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel5.setText("Trenutna cena:");

        jLabel8.setText("Cena vazila od:");

        jLabel9.setText("Cena vazila do:");

        txtKolicina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtIDatumOd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy."))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(50, 50, 50)
                                .addComponent(txtNazivPica, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKolicina))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTrenutnaCena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbJM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbVrstaPica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnIzmeniPice, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSacuvajCenu)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIznosCene, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnIzmeniCenu)
                                .addGap(31, 31, 31)
                                .addComponent(btnObrisiCenu))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNazivPica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbJM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbVrstaPica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTrenutnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnIzmeniPice))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtIDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIznosCene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvajCenu)
                    .addComponent(btnIzmeniCenu)
                    .addComponent(btnObrisiCenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniPiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPiceActionPerformed

        try {
            String naziv = txtNazivPica.getText();
            if (naziv.isEmpty() || txtKolicina.getText().isEmpty() || txtTrenutnaCena.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sva polja moraju "
                        + "biti popunjena!",
                        "Uspesno cuvanje", JOptionPane.PLAIN_MESSAGE);
                return;
            }
            int kolicinaNaStanju = Integer.valueOf(txtKolicina.getText());
            JedinicaMere jm = (JedinicaMere) cmbJM.getSelectedItem();
            VrstaPica vp = (VrstaPica) cmbVrstaPica.getSelectedItem();
            Double trenutnaCena = Double.valueOf(txtTrenutnaCena.getText().replace(',', '.'));
            Pice p = new Pice(pice.getSifraPica(), naziv, kolicinaNaStanju, jm, vp, trenutnaCena, null);
            TableModelCena tmc = (TableModelCena) tblCena.getModel();
            if (tmc.getLista().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Pice mora imati cenu!");
                return;
            }
            p.setOcekivanaCena(tmc.getOcekivanaCena());
            ClientController.getInstance().updatePice(p);
            JOptionPane.showMessageDialog(this, "Pice uspesno izmenjeno!",
                    "Uspesna izmena", JOptionPane.PLAIN_MESSAGE);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(IzmeniPiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }

    }//GEN-LAST:event_btnIzmeniPiceActionPerformed

    private void btnSacuvajCenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajCenuActionPerformed
        if (txtIznosCene.getText().isEmpty() || txtIDatumOd.getText().isEmpty() || txtDatumDo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju "
                    + "biti popunjena!",
                    "Uspesno cuvanje", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        double iznos = Double.valueOf(txtIznosCene.getText().replace(',', '.'));
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
        try {
            Date datod = sdf.parse(txtIDatumOd.getText());
            Date datdo = sdf.parse(txtDatumDo.getText());
            Cena cena = new Cena(pice, datod, datdo, iznos);

            if (cuvanje) {
                ClientController.getInstance().createCena(cena);
                JOptionPane.showMessageDialog(this, "Cena uspesno kreirana!",
                        "Uspesno kreiranje cene", JOptionPane.PLAIN_MESSAGE);
            } else {
                ClientController.getInstance().updateCena(cena);
                JOptionPane.showMessageDialog(this, "Cena uspesno izmenjena!",
                        "Uspesna izmena cene", JOptionPane.PLAIN_MESSAGE);
                btnIzmeniCenu.setEnabled(true);
                btnIzmeniPice.setEnabled(true);
                btnObrisiCenu.setEnabled(true);
                btnSacuvajCenu.setText("Sacuvaj cenu");
                cuvanje = true;
                cenaIzmena = null;

            }
            txtIznosCene.setText("");
            txtIDatumOd.setText("");
            txtDatumDo.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            java.util.logging.Logger.getLogger(IzmeniPiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSacuvajCenuActionPerformed

    private void btnIzmeniCenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniCenuActionPerformed
        int row = tblCena.getSelectedRow();
        if (row != -1) {
            TableModelCena tmc = (TableModelCena) tblCena.getModel();
            Cena c = tmc.getCena(row);
            btnIzmeniCenu.setEnabled(false);
            btnIzmeniPice.setEnabled(false);
            btnObrisiCenu.setEnabled(false);
            btnSacuvajCenu.setText("Izmeni cenu");
            cuvanje = false;
            cenaIzmena = c;
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
            txtDatumDo.setText(sdf.format(cenaIzmena.getDatumDo()));
            txtIDatumOd.setText(sdf.format(cenaIzmena.getDatumOd()));

        }
    }//GEN-LAST:event_btnIzmeniCenuActionPerformed

    private void btnObrisiCenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiCenuActionPerformed
        int row = tblCena.getSelectedRow();
        if (row != -1) {
            TableModelCena tmc = (TableModelCena) tblCena.getModel();
            Cena c = tmc.getCena(row);
            try {
                if (tmc.getLista().isEmpty()) {
                    JOptionPane.showMessageDialog(this,"Ne mozete obrisati jedinu cenu!");
                    return;

                }
                ClientController.getInstance().deleteCena(c);
                JOptionPane.showMessageDialog(this, "Cena uspesno obrisana!",
                        "Uspesno brisanje cene", JOptionPane.PLAIN_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                java.util.logging.Logger.getLogger(IzmeniPiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnObrisiCenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniCenu;
    private javax.swing.JButton btnIzmeniPice;
    private javax.swing.JButton btnObrisiCenu;
    private javax.swing.JButton btnSacuvajCenu;
    private javax.swing.JComboBox cmbJM;
    private javax.swing.JComboBox cmbVrstaPica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCena;
    private javax.swing.JFormattedTextField txtDatumDo;
    private javax.swing.JFormattedTextField txtIDatumOd;
    private javax.swing.JFormattedTextField txtIznosCene;
    private javax.swing.JFormattedTextField txtKolicina;
    private javax.swing.JTextField txtNazivPica;
    private javax.swing.JFormattedTextField txtTrenutnaCena;
    // End of variables declaration//GEN-END:variables

    private void prepareData() {
        txtNazivPica.setText(pice.getNazivPica());
        txtKolicina.setText(String.valueOf(pice.getKolicinaNaStanju()));
        txtTrenutnaCena.setText(String.valueOf(pice.getTrenutnaCena()));
        try {
            ArrayList<VrstaPica> vps = ClientController.getInstance().getAllVrstaPica();
            System.out.println(vps == null);
            cmbVrstaPica.removeAllItems();
            for (VrstaPica vp : vps) {
                cmbVrstaPica.addItem(vp);
            }
            cmbVrstaPica.setSelectedItem(pice.getVrstaPica());
            ArrayList<JedinicaMere> jms = ClientController.getInstance().getAllJedinicaMere();
            cmbJM.removeAllItems();
            for (JedinicaMere jm : jms) {
                cmbJM.addItem(jm);
            }
            cmbJM.setSelectedItem(pice.getJedinicaMere());
        } catch (Exception ex) {
            System.out.println("Klijentova metoda pravi gresku");
            java.util.logging.Logger.getLogger(IzmeniPiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }

    }
}
