/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.ClientController;
import domain.Otpremnica;
import domain.Prijemnica;
import domain.Smena;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 38169
 */
public class PrijemnicaForm extends javax.swing.JDialog {
    Otpremnica otpremnica;
    /**
     * Creates new form PrijemnicaForm
     */
    public PrijemnicaForm(java.awt.Frame parent, boolean modal, Otpremnica otpremnica) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Nova prijemnica");
        this.otpremnica= otpremnica;
        prepareData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSacuvaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSifraPrijemnice = new javax.swing.JFormattedTextField();
        txtNabVrd = new javax.swing.JFormattedTextField();
        txtProdVred = new javax.swing.JFormattedTextField();
        cmbSmena = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSacuvaj.setText("Sacuvaj prijemnicu");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel1.setText("Sifra prijemnice:");

        jLabel2.setText("Nabavna vrednost:");

        jLabel3.setText("Prodajna vrednost:");

        jLabel4.setText("Smena:");

        txtSifraPrijemnice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtNabVrd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        txtProdVred.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        cmbSmena.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addComponent(txtSifraPrijemnice, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSacuvaj)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNabVrd, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtProdVred, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(cmbSmena, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifraPrijemnice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNabVrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdVred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbSmena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnSacuvaj)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
          if (txtNabVrd.getText().isEmpty() || txtProdVred.getText().isEmpty() || txtSifraPrijemnice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju "
                    + "biti popunjena!",
                    "Uspesno cuvanje", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        double nabv = Double.valueOf(txtNabVrd.getText().replace(',', '.'));
        double prodv = Double.valueOf(txtProdVred.getText().replace(',', '.'));
        int sifra = Integer.valueOf(txtSifraPrijemnice.getText());
        Smena s = (Smena) cmbSmena.getSelectedItem();
        Prijemnica p = new Prijemnica(sifra, otpremnica.getDatumIzdavanja(), nabv, prodv, -(nabv- prodv), otpremnica.getZaposleni(), s, otpremnica, otpremnica.getDobavljac());
        try {
            ClientController.getInstance().addPrijemnica(p);
               JOptionPane.showMessageDialog(this, "Prijemnica uspesno kreirana!",
                        "Uspesno kreiranje", JOptionPane.PLAIN_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(PrijemnicaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_btnSacuvajActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbSmena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField txtNabVrd;
    private javax.swing.JFormattedTextField txtProdVred;
    private javax.swing.JFormattedTextField txtSifraPrijemnice;
    // End of variables declaration//GEN-END:variables

    private void prepareData() {
        try {
            cmbSmena.removeAllItems();
            ArrayList<Smena> smene = ClientController.getInstance().getAllSmena();
            for (Smena smena : smene) {
       cmbSmena.addItem(smena);
            }
        } catch (Exception ex) {
            Logger.getLogger(PrijemnicaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
