/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.ClientController;
import domain.Pice;
import domain.Popis;
import domain.StavkaPopisa;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.TableModelStavkaPopisa;

/**
 *
 * @author 38169
 */
public class StavkaPopisaForm extends javax.swing.JDialog {

    Popis popis;
    StavkaPopisa spIzmena;
    boolean cuvanje = true;

    /**
     * Creates new form StavkaPopisaForm
     */
    public StavkaPopisaForm(java.awt.Frame parent, boolean modal, Popis popis) {
        super(parent, modal);
        initComponents();
        this.popis = popis;
        setLocationRelativeTo(null);
        setTitle("Forma stavka popisa");
        System.out.println("Forma: " + popis.toString());
        TableModelStavkaPopisa tmsp = new TableModelStavkaPopisa(popis);
        Thread t = new Thread(tmsp);
        t.start();
        tbl.setModel(tmsp);
        prepareData();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
        txtDatum.setText(sdf.format(popis.getDatumPopisa()));
    }

    public void setPopis(Popis popis) {
        this.popis = popis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JFormattedTextField();
        btnIzmeniPopis = new javax.swing.JButton();
        cmbStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnNovaStavkaPopisa = new javax.swing.JButton();
        btnIzmeniStavkuPopisa = new javax.swing.JButton();
        btnObrisiStavkuPopisa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDatumStavke = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPocKol = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKrajKol = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbPice = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Datum popisa:");

        jLabel2.setText("Status:");

        txtDatum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy."))));

        btnIzmeniPopis.setText("Izmeni popis");
        btnIzmeniPopis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPopisActionPerformed(evt);
            }
        });

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nezakljucen", "Zakljucen" }));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        btnNovaStavkaPopisa.setText(" Nova stavka popisa");
        btnNovaStavkaPopisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaStavkaPopisaActionPerformed(evt);
            }
        });

        btnIzmeniStavkuPopisa.setText("Izmeni stavku popisa");
        btnIzmeniStavkuPopisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniStavkuPopisaActionPerformed(evt);
            }
        });

        btnObrisiStavkuPopisa.setText("Obrisi stavku popisa");
        btnObrisiStavkuPopisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuPopisaActionPerformed(evt);
            }
        });

        jLabel3.setText("Datum popisa:");

        txtDatumStavke.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy."))));

        jLabel4.setText("Pocetna kolicina:");

        txtPocKol.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel5.setText("Krajnja kolicina:");

        txtKrajKol.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel6.setText("Pice:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(31, 31, 31)
                                .addComponent(txtPocKol, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDatumStavke, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKrajKol, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(cmbPice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(30, 30, 30)
                        .addComponent(btnNovaStavkaPopisa)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIzmeniStavkuPopisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisiStavkuPopisa)
                        .addGap(77, 77, 77))))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIzmeniPopis)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnIzmeniPopis)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeniStavkuPopisa)
                    .addComponent(btnObrisiStavkuPopisa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatumStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPocKol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnNovaStavkaPopisa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKrajKol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaStavkaPopisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaStavkaPopisaActionPerformed
        if (txtPocKol.getText().isEmpty() || txtKrajKol.getText().isEmpty() || txtDatumStavke.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!");
            return;
        }
        Pice pice = (Pice) cmbPice.getSelectedItem();
        double pocKol = Double.parseDouble(txtPocKol.getText().replace(',', '.'));
        Double krajKol = Double.parseDouble(txtKrajKol.getText().replace(',', '.'));
        double prodataKol = pocKol - krajKol;
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");

        try {
            Date datum = sdf.parse(txtDatumStavke.getText());
            StavkaPopisa sp = new StavkaPopisa(popis, -1, pocKol, krajKol, prodataKol, datum, pice);
            if (cuvanje) {
                ClientController.getInstance().insertStavkaPopisa(sp);
                JOptionPane.showMessageDialog(this, "Stavka popisa uspesno dodata!", "Uspesno cuvanje", JOptionPane.INFORMATION_MESSAGE);
            } else {
                sp.setRedBrojStavke(spIzmena.getRedBrojStavke());
                ClientController.getInstance().updateStavkaPopisa(sp);
                JOptionPane.showMessageDialog(this, "Stavka popisa uspesno izmenjena!", "Uspesna izmena", JOptionPane.INFORMATION_MESSAGE);
                spIzmena = null;
                btnIzmeniStavkuPopisa.setEnabled(true);
                btnObrisiStavkuPopisa.setEnabled(true);
                btnNovaStavkaPopisa.setText("Nova stavka popisa");
                cuvanje = true;

            }

            txtDatumStavke.setText("");
            txtKrajKol.setText("");
            txtPocKol.setText("");
            cmbPice.setSelectedIndex(0);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            txtDatumStavke.setText("");
            txtKrajKol.setText("");
            txtPocKol.setText("");
            cmbPice.setSelectedIndex(0);
            spIzmena = null;
            btnIzmeniStavkuPopisa.setEnabled(true);
            btnObrisiStavkuPopisa.setEnabled(true);
            btnNovaStavkaPopisa.setText("Nova stavka popisa");
            cuvanje = true;
            Logger.getLogger(StavkaPopisaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNovaStavkaPopisaActionPerformed

    private void btnIzmeniPopisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPopisActionPerformed
        if (txtDatum.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Polje datuma mora biti popunjeno!");
            return;
        }
        String status = (String) cmbStatus.getSelectedItem();
        TableModelStavkaPopisa tmsp = (TableModelStavkaPopisa) tbl.getModel();
        double ukupanPromet = tmsp.getUkupanPromet();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yy.MM.dd. HH:mm:ss,S", Locale.getDefault());
        String vreme = simpleDateFormat.format(new Date());
        popis.setStatus(status);
        popis.setUkupanPromet(ukupanPromet);
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");

        try {
            Date datum = sdf.parse(txtDatum.getText());
            popis.setDatumPopisa(datum);
            ClientController.getInstance().updatePopis(popis);
            JOptionPane.showMessageDialog(null, "Popis uspesno izmenjen!", "Uspesna izmena", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            Logger.getLogger(StavkaPopisaForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnIzmeniPopisActionPerformed

    private void btnIzmeniStavkuPopisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniStavkuPopisaActionPerformed
        int selectedRow = tbl.getSelectedRow();
        if (selectedRow != -1) {
            TableModelStavkaPopisa tme = (TableModelStavkaPopisa) tbl.getModel();
            StavkaPopisa sp = tme.getStavkaPopis(selectedRow);
            spIzmena = sp;
            btnIzmeniStavkuPopisa.setEnabled(false);
            btnObrisiStavkuPopisa.setEnabled(false);
            btnNovaStavkaPopisa.setText("Izmeni stavku popisa");
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
            txtDatumStavke.setText(sdf.format(sp.getDatumPopisa()));
            txtKrajKol.setText(String.valueOf(sp.getKrajnjaKol()));
            txtPocKol.setText(String.valueOf(sp.getPocetnaKol()));
            cmbPice.setSelectedItem(sp.getPice());
            cuvanje = false;
        }
    }//GEN-LAST:event_btnIzmeniStavkuPopisaActionPerformed

    private void btnObrisiStavkuPopisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuPopisaActionPerformed
        int selectedRow = tbl.getSelectedRow();
        if (selectedRow != -1) {
            TableModelStavkaPopisa tme = (TableModelStavkaPopisa) tbl.getModel();
            StavkaPopisa sp = tme.getStavkaPopis(selectedRow);
            try {
                ClientController.getInstance().deleteStavkaPopisa(sp);
                JOptionPane.showMessageDialog(this, "Stavka popisa uspesno obrisana!", "Uspesno brisanje", JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                Logger.getLogger(StavkaPopisaForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnObrisiStavkuPopisaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniPopis;
    private javax.swing.JButton btnIzmeniStavkuPopisa;
    private javax.swing.JButton btnNovaStavkaPopisa;
    private javax.swing.JButton btnObrisiStavkuPopisa;
    private javax.swing.JComboBox cmbPice;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JFormattedTextField txtDatum;
    private javax.swing.JFormattedTextField txtDatumStavke;
    private javax.swing.JFormattedTextField txtKrajKol;
    private javax.swing.JFormattedTextField txtPocKol;
    // End of variables declaration//GEN-END:variables

    private void prepareData() {
        try {
            cmbPice.removeAllItems();
            ArrayList<Pice> pica = ClientController.getInstance().getAllPice();
            for (Pice pice : pica) {
                cmbPice.addItem(pice);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }
}
